name: build docker images and run tests for multi containers app
on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: build all docker images
        id: app-images-build
        run: |
          docker build -t rafzenx/multi-client ./client
          docker build -t rafzenx/multi-nginx ./nginx
          docker build -t rafzenx/multi-server ./server
          docker build -t rafzenx/multi-worker ./worker

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: push all images to Dockerhub
        run: |
          docker push rafzenx/multi-client:latest
          docker push rafzenx/multi-nginx:latest
          docker push rafzenx/multi-server:latest
          docker push rafzenx/multi-worker:latest
      
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: multi-docker
          environment_name: Multi-docker-env
          version_label: 12345
          region: ew-west-3
          deployment_package: deploy.zip


 